[package]
name = "cli-utilities"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "echom"
path = "src/echom/echom.rs"

[[bin]]
name = "catg"
path = "src/catg/catg.rs"

[dependencies]
lexopt = "0.3.0"
